#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

thirdParty/Allwmake

# Compile OpenFOAM libraries and applications

applications/Allwmake $targetType $*
src/Allwmake $targetType $*
#------------------------------------------------------------------------------
